FROM --platform=linux/amd64 ubuntu:20.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential

COPY . /tiny-compiler
WORKDIR /tiny-compiler
RUN make

FROM ubuntu:20.04 as package
COPY --from=builder /tiny-compiler/compiler /
